language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    #      - sourceline: "ppa:beineri/opt-qt-5.10.1-trusty"
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - gcc-7
      - g++-7

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew update ;
    brew install qt5 cmake ;
    brew link --force qt ;
    fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    export CC=gcc-7 ;
    export CXX=g++-7 ;
    fi
  - cmake --version
  - cmake .
  - cmake --build .
  - cmake --build . --target package
  - doxygen Doxyfile

before_script:
  - sudo apt-get install libboost-test-dev -y
  - echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
  - echo ""
  - sudo apt-get update -qq


deploy:
  provider: script
  skip_cleanup: true
  script:
    - curl -T print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -u stirlitzi:$BINTRAY_API_KEY "https://api.bintray.com/content/test195/test195/otus-4-master/$TRAVIS_BUILD_NUMBER/print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"

    - provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local-dir: docs/html